# default configuration
baseURL = "https://www.zerowastecat.org"
languageCode = "cat-es"
summaryLength = "10"
theme = "kross-hugo"
title = "Zero Waste Catalunya"

[markup.goldmark.renderer]
unsafe= true

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "Nosaltres"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Fotos"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contacte"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/logo.svg"
# theme color
theme_color = "#20c997"
# contact info
phone = "Pel's amics"
email = "@zerowaste.cat"
address = "La Vall de l'Arrabassada, Tarragon, Catalunya"
# meta description
author = "Oriol Guiu"
description = "El tiempo para reaccionar se acaba!"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; theme by hugo"


# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/zerowastecat.org"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/zerowaste.cat/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/search?q=zerowaste"